[package]
name = "spinners-rs"
version = "0.1.0"
authors = ["dragfire <asem.devajit@gmail.com>"]
edition = "2018"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.55"
